-- ====================================================================
-- APPLICATION_HISTORYテーブル作成スクリプト
-- 申請履歴テーブル（休日出勤申請、残業申請、早朝勤務申請、振替申請など）
-- ====================================================================

USE teamspirit_db;

-- APPLICATION_HISTORYテーブルが存在しない場合のみ作成
CREATE TABLE IF NOT EXISTS APPLICATION_HISTORY (
    APPLICATION_ID BIGINT AUTO_INCREMENT NOT NULL COMMENT '申請ID: 主キー。申請履歴を一意に識別するID（自動採番）',
    EMPLOYEE_ID VARCHAR(50) NOT NULL COMMENT '従業員ID: 外部キー。どの従業員の申請か。EMPLOYEEテーブルを参照',
    APPLICATION_TYPE VARCHAR(20) NOT NULL COMMENT '申請種別: HOLIDAY_WORK=休日出勤申請、OVERTIME=残業申請、EARLY_WORK=早朝勤務申請、TRANSFER=振替申請',
    TARGET_START_DATE DATE NOT NULL COMMENT '対象開始日: 申請対象期間の開始日。形式YYYY-MM-DD',
    TARGET_END_DATE DATE NOT NULL COMMENT '対象終了日: 申請対象期間の終了日。形式YYYY-MM-DD',
    OVERTIME_HOURS DECIMAL(5,2) COMMENT '残業時間: 残業申請の場合の残業時間（時間単位）。例: 2.00=2時間',
    REASON TEXT COMMENT '申請理由: 申請の理由や詳細',
    APPROVAL_STATUS VARCHAR(20) DEFAULT 'PENDING' COMMENT '承認状態: PENDING=申請中、APPROVED=承認済、REJECTED=却下',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時: レコード作成日時（自動設定）',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時: レコード更新日時（自動更新）',
    PRIMARY KEY (APPLICATION_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID) ON DELETE CASCADE,
    INDEX IDX_EMP_TYPE (EMPLOYEE_ID, APPLICATION_TYPE),
    INDEX IDX_TARGET_DATE (TARGET_START_DATE, TARGET_END_DATE),
    INDEX IDX_APPROVAL (APPROVAL_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='申請履歴';
